[package]
name = "bevy_hard_marble"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_rapier3d = { version = "0.23.0", features = ["debug-render-3d", "wasm-bindgen"] }
